- name: Deploy App using Docker
  when: deployment_way == "docker"
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image }}"
    state: started
    published_ports:
      - "{{ ports }}"
    restart_policy: unless-stopped
    restart: true
    recreate: true

- name: Deploy App using Docker Compose
  when: deployment_way == "docker_compose"
  block:
    - name: Create directory
      file:
        path: "/app_python"
        state: directory

    - name: Create docker compose file
      template:
        src: "docker-compose.yml.j2"
        dest: "/app_python/docker-compose.yml"

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: "/app_python"
        build: false
