- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker

- include_tasks: /home/mpiniagin/stuff/S24-DevOps-labs/ansible/roles/docker/tasks/install_docker.yml

- include_tasks: /home/mpiniagin/stuff/S24-DevOps-labs/ansible/roles/docker/tasks/install_compose.yml