name: CI

on:
  push:
    branches:
      - main
      - Lab3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Dependencies
        run: |
          cd app_python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linter
        run: |
          cd app_python
          pip install flake8
          flake8 .

      - name: Tests
        run: |
          cd app_python
          python app.py &
          sleep 5
          cd tests
          python app_test.py

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd app_python
          docker build -t ozurexus/my-flask-app:latest .
          docker tag ozurexus/my-flask-app:latest ozurexus/my-flask-app:latest
          docker push ozurexus/my-flask-app:latest